import * as fs from 'fs';
import * as path from 'path';
import minimist from 'minimist';
import { readSpreadsheet } from './spreadsheet-reader';
import { TestCase } from './file-reader';

function generateSpecContent(testCases: TestCase[], baseEnvFile: string = '.env'): string {
  let content = `// Auto-generated by test-generator.ts — DO NOT EDIT MANUALLY
import { test, expect } from '@playwright/test';

const BASE_URL = process.env.BASE_URL!;
const ACCOUNT = process.env.ACCOUNT!;
const PASSWORD = process.env.PASSWORD!;

test.beforeEach(async ({ page }) => {
  if (BASE_URL) {
    await page.goto(BASE_URL);
  }
  // Optional: add your generic login logic here if needed
});

`;

  for (const tc of testCases) {
    // Escaping newlines in description and test block to avoid syntax errors
    const titleSafe = tc['judul-test-case'].replace(/'/g, "\\'").replace(/\n/g, " ");
    const preconditionComment = tc['precondition'] ? tc['precondition'].split('\n').map((s: string) => `  // Precondition: ${s}`).join('\n') : "  // No precondition provided";
    const stepsComment = tc['test-steps'] ? tc['test-steps'].split('\n').map((s: string) => `  // Step: ${s}`).join('\n') : "  // No steps provided";
    const expectedComment = tc['expected-result'] ? tc['expected-result'].split('\n').map((s: string) => `  // Expected: ${s}`).join('\n') : "  // No expected result provided";
    
    content += `test('${tc['tc-id']} — ${titleSafe}', async ({ page }) => {
${preconditionComment}
${stepsComment}
${expectedComment}
  
  // TODO: Implement test logic
  // expect(true).toBe(true);
});

`;
  }

  return content;
}

async function main() {
  const args = minimist(process.argv.slice(2));

  try {
    console.log('Reading test data from Google Spreadsheet...');
    const testCases = await readSpreadsheet();
    console.log(`Found ${testCases.length} test cases.`);

    const specContent = generateSpecContent(testCases);

    const outputDir = path.join(__dirname, '..', 'tests');
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }

    const sheetName = process.env.SHEET_NAME ?? 'spreadsheet';
    const sanitizedName = sheetName.replace(/[^a-zA-Z0-9_-]/g, '_');
    const outFilePath = path.join(outputDir, `${sanitizedName}.spec.ts`);

    fs.writeFileSync(outFilePath, specContent, 'utf-8');
    console.log(`Spec file generated: ${outFilePath}`);

    // Also output JSON array of TestCase into data/
    const dataDir = path.join(__dirname, '..', 'data');
    if (!fs.existsSync(dataDir)) fs.mkdirSync(dataDir, { recursive: true });
    const jsonOutPath = path.join(dataDir, `${sanitizedName}.json`);
    fs.writeFileSync(jsonOutPath, JSON.stringify(testCases, null, 2), 'utf-8');
    console.log(`JSON data file generated: ${jsonOutPath}`);

  } catch (error: any) {
    console.error(`Error: ${error.message}`);
    process.exit(1);
  }
}

main();
